services:
  postgres: # db zabbix
    image: ${ZABBIX_DB_IMAGE}:${ZABBIX_DB_VERSION}
    container_name: db-zabbix-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: # named
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    mem_limit: 400m
    restart: unless-stopped
  
  zabbix-server: # back zabbix
    image: ${ZABBIX_SERVER_IMAGE}:${ZABBIX_SERVER_VERSION}
    container_name: back-zabbix-server
    depends_on:
      - postgres
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_ZABBIX_PORT}:${CONTAINER_ZABBIX_PORT}"
    networks:
      - zabbix-net
    mem_limit: 256m
    restart: unless-stopped

  zabbix-web: # front zabbix
    image: ${ZABBIX_WEB_IMAGE}:${ZABBIX_WEB_VERSION}
    container_name: front-zabbix-web
    depends_on:
      - postgres
      - zabbix-server
    environment:
      environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${HOST_PHP_PORT}:${CONTAINER_PHP_PORT}"
    networks:
      - zabbix-net
    mem_limit: 512m
    restart: unless-stopped
  
  prometheus:
    image: ${PROMETHEUS_IMAGE}:${PROMETHEUS_VERSION}
    container_name: prometheus
    volumes: # bind
     - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'
    networks:
      - zabbix-net
    mem_limit: 256m
    restart: unless-stopped

  grafana:
    image: ${GRAFANA_IMAGE}:${GRAFANA_VERSION}
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "${HOST_GRAFANA_PORT}:${CONTAINER_GRAFANA_PORT}"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS}
      GF_SERVER_DOMAIN: monitoramento.alancruztec.com.br
      GF_SERVER_ROOT_URL: https://monitoramento.alancruztec.com.br/
      GF_SERVER_PROTOCOL: http
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - zabbix-net
    mem_limit: 1250m
    restart: unless-stopped
    
volumes:
  postgres_data:
  grafana_data:

networks:
  zabbix-net: